### ISSUE TITLE
white border on forward button?

### ISSUE THREAD

**Issue by Skrell** [Lootyhoof/australium#1]
I'm sorry to leave this here but I don't know how else to contact the developer.  I'm using and loving this theme but wanted to change it a bit to have a darker toolbar background when I noticed that the forward has this weird white border around it that I can't seem to remove no matter what code I use with the stylish addon.  Could you please point me to where in the theme the forward button's appearance is set keeping in mind I'm no theme developer and just a CSS hacker.

**Comment by Lootyhoof** [comment]
Could you provide a screenshot to demonstrate this issue? What OS are you using?

As for where it is styled, look for `#forward-button` and `#unified-back-forward-button` in `browser/browser.css`.

**Comment by Skrell** [comment]
Yes I'll sent you one later tonight from home.  Thank you for responding!
I'm using Win8.1 64bit.  Do you have any experience with the stylish addon?

**Comment by Lootyhoof** [comment]
Thanks for clarifying on the OS. Yes, Stylish is typically what I use to try styles out before applying them into my themes, where possible.

**Comment by Skrell** [comment]
Ok so here is what i'm talking about.  Note that this is running my stylish
script which is why the back button looks the way it does...currently there
is NOTHING i have been able to do in stylish to make the forward button
look the same.  :(

[image: Inline image 1]

**Comment by Skrell** [comment]
Here is a file version in case you can't see the pasted image.

**Comment by Lootyhoof** [comment]
There are no images in either of your comments, unfortunately.

**Comment by Skrell** [comment]
Maybe i can't send you files through Github ...what is your normal email
address?

**Comment by Lootyhoof** [comment]
In any case, I've identified the issue to stem to Firefox itself (where most of the styling for this comes from), due to it using a `ThreeDShadow` for the border colour. See below, what a dark toolbar looks like in Firefox:

![Firefox](http://i.imgur.com/As0PI6F.png)

While admittedly this does look more uniform than my implementation, which is a mix-up of Firefox and Pale Moon styles, it is a design choice. If you want to have darker toolbars, I would suggest using personas rather than manually changing the background shading (use [Persona Switcher](https://addons.mozilla.org/en-GB/firefox/addon/personaswitcher/) for that). Alternatively, you can play about with this element in CSS. For example, the following will remove the border completely:

```
window:not([chromehidden~=toolbar]) #navigator-toolbox[iconsize=large][mode=icons] > :-moz-any(#nav-bar[currentset*="unified-back-forward-button,urlbar-container"],#nav-bar:not([currentset])) > #unified-back-forward-button > #forward-button > .toolbarbutton-icon {
  border: none !important;
}
```

**Comment by Skrell** [comment]
Thank you that is a good starting point for me!

Can you please look at these other 2 issues?  1)  There is extra space on
the left of the tabbar and 2) Omnisidebar looks awful.  :
http://oi64.tinypic.com/wvpjyu.jpg
http://oi65.tinypic.com/war9di.jpg

**Comment by Skrell** [comment]
I fixed #1, but #2 is definitely going to take some work.  :(

**Comment by Lootyhoof** [comment]
The tabbar issue was a design choice due to the design of the Australis tabs, though I'm glad you found a way to workaround this for your CSS. For OmniSidebar, [this CSS](https://gist.github.com/Lootyhoof/6703431c8b7548b78011) appears to work; credit to the OmniSidebar author, as it's mostly a paste of the CSS used in post-Australis versions.

**Comment by Skrell** [comment]
WOW thank you that worked fantastic!   Also I wanted to thank you for
contributing so much to Palemoon as it's a browser I greatly believe in and
hope to see more people try!   With your great themes I definitely can see
more people being open to it!

--Vince

**Comment by Lootyhoof** [comment]
No problem, glad to help. With regards to your earlier comment about an email address, this should now be public on my profile page, should anyone else need to be in touch. 

Enjoy!
